CREATE TABLE [dbo].[User]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Email] NVARCHAR(320) NOT NULL UNIQUE,
	[Password] VARBINARY(64) NOT NULL,
	[Salt] UNIQUEIDENTIFIER NOT NULL
)
